books_web/books_web/books/urls.py
from django import urls

urlpatterns = [

]

books_web/books_web/books_web/urls.py
from django.contrib import admin
from django.urls import path,re_path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('index.urls')),
    re_path('books/', include('books.urls')),
]

books_web/books_web/index/forms.py
from django import forms
from django.core.exceptions import ValidationError


class userForm(forms.Form):
    #用户名
    uname = forms.CharField(
        min_length=3,
        label='用户名',
        error_messages={
            "required" : "不能为空",
            "invalid": "格式错误",
            "min_length": "用户名最短3位"
        },
        widget=forms.TextInput(attrs={'class':'layui-input'})
    )
    #密码
    upasswd = forms.CharField(
        min_length=3,
        label="密码",
        error_messages={
            "required": "不能为空",
            "min_length": "密码最短3位"
        },
        widget=forms.PasswordInput(attrs={'class': 'layui-input'})
    )
    #确认密码
    re_upasswd = forms.CharField(
        min_length=3,
        label="确认密码",
        error_messages={
            "required": "不能为空",
            "min_length": "密码最短3位"
        },
        widget=forms.PasswordInput(attrs={'class': 'layui-input'})
    )

    uemail = forms.EmailField(
        label="邮箱地址",
        error_messages={
            "required": "不能为空",
        },
        widget=forms.EmailInput(attrs={'class': 'layui-input'})
    )

books_web/books_web/index/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <link rel="stylesheet" href="/static/Books.css">
    <link rel="stylesheet" href="/static/layui/css/layui.css">
    <style>

    </style>
</head>
<body>
<div id="Head" class="booksHead">
    <div class="navlist" id="mainNavBox" style="z-index: 300!important;">
        <ul>
            <li class="logo" style="text-align: left;"><a href=""></a>
            </li>
            <li>
                <a href="" style="padding: 10px 0px 0px;">首页</a>
                <span class="NavLine"></span>
            </li>
            <li>
                <a href="">books</a>
                <span class="NavLine"></span>
                <div class="subNav" style="display: none;">
                    <span></span>
                    <ul>
                        <li>1</li>
                        <li>2</li>
                        <li>3</li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
    <div id="content" class="Content">
        <div class="FocusAd">
            <div style="width: 100%;height: 2px;"></div>
            <div class="Focus" style="background-color: #00F7DE">
                #推荐栏
                <div class="foucsTab" >

                </div>
            </div>
        </div>
        <span class="blank20"></span>
        <div class="list_top">
            <h2>优先推荐</h2>

            <div class="layui-row">
                {% for i in book_list %}

                <div class="layui-col-md4">

                    <div class="layui-row">
                        <div class="layui-col-md8">
                            <a href="">
                            <img src="{{ i.book_img_url }}" alt="{{ i.book_name }}" class="index_list_top_img">
                                </a>
                        </div>
                        <div class="layui-col-md4 index_book_info">
                            <ul class="books_info">
                                <li><h3>{{ i.book_name }}</h3></li>
                                <li>
                                    <span>作者:</span>
                                    {{ i.book_auth }}
                                </li>
                                <li>
                                    <span>价格:</span>
                                    {{ i.book_price }}￥
                                </li>

                                <li>
                                    <span>简介:</span>
                                    {{ i.book_introduction }}
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>

    </div>
    <div class="footArea">
        <div class="footBottom">
            <p>
                Copyright 2007 - 2019 京ICP证 京公网安备号
            </p>
            <p>
                felix 出版
            </p>
        </div>
    </div>

</div>
</body>
</html>

books_web/books_web/index/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/layui/css/layui.css">
    <script src="/static/layui/layui.js"></script>
    <title>login</title>
    <style>
        span{
            color: #FF5722;
            font-size: larger;
        }
        #remember_passwd{
            display: inline;
        }
    </style>
</head>
<body>

<div class="layui-row">
    <div class="layui-col-md4 layui-col-md-offset4" style="border-radius: 5px">
        <form action="/login/" class="layui-form layui-bg-gray" method="post" >
            {% csrf_token %}

            <div class="layui-form-item">
                <div class="layui-col-md9">
                <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
                    <legend>登录页</legend>
                </fieldset>
                </div>
                <div class="layui-col-md3">
                    <div style="margin:10px 0 0 50px; ">
                        <a href="{% url 'register' %}"><span>注册</span></a>
                    </div>
                </div>
            </div>
            <div class="layui-form-item">
                <img src="{% static "image/index.jpeg" %}" alt="" style="width: 100%">
            </div>

            <div class="layui-form-item">
                <label for="" class="layui-form-label">用户名</label>
                <div class="layui-input-block">
                    <input type="text" name="uname"  placeholder="" autocomplete="off" class="layui-input" style="width: 80%">
                </div>
            </div>

            <div class="layui-form-item">
                <label for="" class="layui-form-label">密码</label>
                <div class="layui-input-block">
                    <input type="password" name="upasswd" placeholder="" autocomplete="off" class="layui-input" style="width: 80%">
                </div>
            </div>

            <div class="layui-form-item">
                <div class="layui-input-block">
                    <input type="checkbox" name="remb_passwd" lay-skin="primary" title="记住密码" checked="" id="remember_passwd">
                    记住密码
                </div>
            </div>

            <div class="layui-form-item">
                <label for=""></label>
                <div class="layui-input-block layui-row">
                    <button class="layui-btn" name="btn" value="login">登录</button>

                </div>

            </div>
            <div style="height: 20px">
                <label for=""></label>
                <sapn class="layui-input-block" style="color: #FF5722;">
                    <b>{{ errmsg }}</b>
                </sapn>

            </div>


        </form>
    </div>

</div>

</body>
</html>

<script>

    layui.use('button',{})

</script>

books_web/books_web/index/templates/register.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register</title>
    <link rel="stylesheet" href="/static/layui/css/layui.css">
    <script src="/static/layui/layui.js"></script>
    <style>
        #a_href{
            float: left;
            position: relative;
        }
        span{
            color: #FF5722;
            font-size: larger;
        }
        .layui-input{
            width: 80%;
        }
    </style>

</head>
<body>

<div class="layui-row" >
    <div class="layui-col-md4 layui-col-md-offset4" >
        <div style="height: 20px"></div>
        <form action="/register/" method="post" class="layui-form" style="outline: outset">
            {%csrf_token%}
            <div class="layui-col-md9">
            <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
                <legend>注册页面</legend>
            </fieldset>
            </div>
            <div class="layui-col-md3" id="a_href">
                <div style="margin:10px 0 0 50px; ">
                    <a href="{% url 'login' %}"><span>登录</span></a>
                </div>
            </div>

{#            用户名#}
            <div class="layui-form-item">
                <label for="{{ uform.uname.id_for_label }}"
                    class="layui-form-label">{{ uform.uname.label }}</label>
                 <div class="layui-input-block">
                {{ uform.uname }}
                <span class="help-block" >{{ uform.uname.errors.0 }}</span>
                     <span id="errmsg_uname"></span>
                 </div>
            </div>

{#            密码#}
            <div class="layui-form-item">
                <label for="{{ uform.upasswd.id_for_label }}"
                    class="layui-form-label">{{ uform.upasswd.label }}</label>
                 <div class="layui-input-block">
                {{ uform.upasswd }}
                <span class="help-block">{{ uform.upasswd.errors.0 }}</span>
                 </div>
            </div>

{#            确认密码#}
            <div class="layui-form-item">
                <label for="{{ uform.re_upasswd.id_for_label }}"
                    class="layui-form-label">{{ uform.re_upasswd.label }}</label>
                 <div class="layui-input-block">
                {{ uform.re_upasswd }}
                <span class="help-block">{{ uform.re_upasswd.errors.0 }}</span>
                     <span id="errmsg_re_upasswd"></span>
                 </div>
            </div>

{#            邮件地址#}
            <div class="layui-form-item">
                <label for="{{ uform.uemail.id_for_label }}"
                    class="layui-form-label">{{ uform.uemail.label }}</label>
                 <div class="layui-input-block">
                {{ uform.uemail }}
                <span class="help-block">{{ uform.uemail.errors.0 }}</span>
                     <span id="errmsg_uemail"></span>
                 </div>
            </div>


            <div class="layui-form-item">
                <label for=""></label>
                <div class="layui-input-block">
                    <button class="layui-btn" name="btn" value="register" style="margin: 0 0 10px 0">注册</button>

                </div>
            </div>
        </form>
        <div class="layui-form-item">
            <div id="errmsg" style="color: #FF5722"></div>
        </div>
    </div>
</div>

</body>
</html>


<script>


    layui.use('layer',function(){
    var $ = layui.$;
    var layer = layui.layer;
    //触发验证用户名
    $('#id_uname').mouseout(function () {
        var uname = $(this).val();
        $.get("/check/",{'uname':uname},function (ret) {
            if (ret['Booldata']=="True"){
                $("#errmsg_uname").html("用户名已存在");
            }else{
                $("#errmsg_uname").html("");
            };
        });
        });
    //触发验证邮箱地址
    $('#id_uemail').mouseout(function () {
        var uemail = $(this).val();
        $.get("/check/",{'uemail':uemail},function (ret) {
            if (ret['Booldata']=="True"){

                $("#errmsg_uemail").html("邮箱地址已存在");

            }else{
                $("#errmsg_uemail").html("");
            };
        });
        });


    //触发验证密码是否一致
    $('#id_re_upasswd').mouseout(function () {
        var re_upasswd = $(this).val();
        var upasswd = $("#id_upasswd").val();
        if (re_upasswd == upasswd){
            $("#errmsg_re_upasswd").html("");
        }else{
            $("#errmsg_re_upasswd").html("密码不一致");
        };

    });
    });

</script>

books_web/books_web/index/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>

    <style>

    </style>
</head>
<body>
</body>
</html>